name: 163 Appeal

on:
  schedule:
  - cron: "0,10,20,30,40,50 * * * *"
  workflow_dispatch:

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: 163 appeal
        id: run_script
        run: |
          python 163appeal.py
          echo ::set-output name=exit_code::${PIPESTATUS[0]}
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "163 latest updated" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      - name: Send Notification
        if: ${{ steps.run_script.outputs.exit_code == 0 }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            $(cat 163-output.txt)
