name: javdb check

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests BeautifulSoup
      - name: javdb check
        id: run_script
        run: |
          python javdb.py
      - name: Commit results
        id: commiting
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "javdb updated" || echo "NEED-REPORT=false" >> $GITHUB_ENV
          git push origin || echo "NEED-REPORT=false" >> $GITHUB_ENV
      - name: 输出 Python 脚本运行结果
        id: python-output
        run: 
          if [ -f "javdb-prompt.txt" ]; then
              echo "RESULT=$(cat javdb-prompt.txt)" >> $GITHUB_OUTPUT
              echo "NEED-REPORT=true" >> $GITHUB_ENV
          else
            echo "NEED-REPORT=false" >> $GITHUB_ENV
          fi
      - name: Send Notification
        if: ${{ env.NEED-REPORT != 'false' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ steps.python-output.outputs.RESULT }}
